/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TuktukRouteImport } from './routes/tuktuk'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TuktukRoute = TuktukRouteImport.update({
  id: '/tuktuk',
  path: '/tuktuk',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soporte': typeof SoporteRoute
  '/tuktuk': typeof TuktukRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soporte': typeof SoporteRoute
  '/tuktuk': typeof TuktukRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soporte': typeof SoporteRoute
  '/tuktuk': typeof TuktukRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacidad'
    | '/sitemap.xml'
    | '/soporte'
    | '/tuktuk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/privacidad' | '/sitemap.xml' | '/soporte' | '/tuktuk'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/privacidad'
    | '/sitemap.xml'
    | '/soporte'
    | '/tuktuk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PrivacidadRoute: typeof PrivacidadRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoporteRoute: typeof SoporteRoute
  TuktukRoute: typeof TuktukRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tuktuk': {
      id: '/tuktuk'
      path: '/tuktuk'
      fullPath: '/tuktuk'
      preLoaderRoute: typeof TuktukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PrivacidadRoute: PrivacidadRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoporteRoute: SoporteRoute,
  TuktukRoute: TuktukRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
