/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TuktukRouteImport } from './routes/tuktuk'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as SolucionesRouteImport } from './routes/soluciones'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacidadIndexRouteImport } from './routes/privacidad/index'
import { Route as PrivacidadVrixoraRouteImport } from './routes/privacidad/vrixora'
import { Route as PrivacidadTuktukRouteImport } from './routes/privacidad/tuktuk'

const TuktukRoute = TuktukRouteImport.update({
  id: '/tuktuk',
  path: '/tuktuk',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucionesRoute = SolucionesRouteImport.update({
  id: '/soluciones',
  path: '/soluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadIndexRoute = PrivacidadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivacidadRoute,
} as any)
const PrivacidadVrixoraRoute = PrivacidadVrixoraRouteImport.update({
  id: '/vrixora',
  path: '/vrixora',
  getParentRoute: () => PrivacidadRoute,
} as any)
const PrivacidadTuktukRoute = PrivacidadTuktukRouteImport.update({
  id: '/tuktuk',
  path: '/tuktuk',
  getParentRoute: () => PrivacidadRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacidad': typeof PrivacidadRouteWithChildren
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soluciones': typeof SolucionesRoute
  '/soporte': typeof SoporteRoute
  '/tuktuk': typeof TuktukRoute
  '/privacidad/tuktuk': typeof PrivacidadTuktukRoute
  '/privacidad/vrixora': typeof PrivacidadVrixoraRoute
  '/privacidad/': typeof PrivacidadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soluciones': typeof SolucionesRoute
  '/soporte': typeof SoporteRoute
  '/tuktuk': typeof TuktukRoute
  '/privacidad/tuktuk': typeof PrivacidadTuktukRoute
  '/privacidad/vrixora': typeof PrivacidadVrixoraRoute
  '/privacidad': typeof PrivacidadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacidad': typeof PrivacidadRouteWithChildren
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soluciones': typeof SolucionesRoute
  '/soporte': typeof SoporteRoute
  '/tuktuk': typeof TuktukRoute
  '/privacidad/tuktuk': typeof PrivacidadTuktukRoute
  '/privacidad/vrixora': typeof PrivacidadVrixoraRoute
  '/privacidad/': typeof PrivacidadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacidad'
    | '/servicios'
    | '/sitemap.xml'
    | '/soluciones'
    | '/soporte'
    | '/tuktuk'
    | '/privacidad/tuktuk'
    | '/privacidad/vrixora'
    | '/privacidad/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/servicios'
    | '/sitemap.xml'
    | '/soluciones'
    | '/soporte'
    | '/tuktuk'
    | '/privacidad/tuktuk'
    | '/privacidad/vrixora'
    | '/privacidad'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/privacidad'
    | '/servicios'
    | '/sitemap.xml'
    | '/soluciones'
    | '/soporte'
    | '/tuktuk'
    | '/privacidad/tuktuk'
    | '/privacidad/vrixora'
    | '/privacidad/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PrivacidadRoute: typeof PrivacidadRouteWithChildren
  ServiciosRoute: typeof ServiciosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolucionesRoute: typeof SolucionesRoute
  SoporteRoute: typeof SoporteRoute
  TuktukRoute: typeof TuktukRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tuktuk': {
      id: '/tuktuk'
      path: '/tuktuk'
      fullPath: '/tuktuk'
      preLoaderRoute: typeof TuktukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soluciones': {
      id: '/soluciones'
      path: '/soluciones'
      fullPath: '/soluciones'
      preLoaderRoute: typeof SolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad/': {
      id: '/privacidad/'
      path: '/'
      fullPath: '/privacidad/'
      preLoaderRoute: typeof PrivacidadIndexRouteImport
      parentRoute: typeof PrivacidadRoute
    }
    '/privacidad/vrixora': {
      id: '/privacidad/vrixora'
      path: '/vrixora'
      fullPath: '/privacidad/vrixora'
      preLoaderRoute: typeof PrivacidadVrixoraRouteImport
      parentRoute: typeof PrivacidadRoute
    }
    '/privacidad/tuktuk': {
      id: '/privacidad/tuktuk'
      path: '/tuktuk'
      fullPath: '/privacidad/tuktuk'
      preLoaderRoute: typeof PrivacidadTuktukRouteImport
      parentRoute: typeof PrivacidadRoute
    }
  }
}

interface PrivacidadRouteChildren {
  PrivacidadTuktukRoute: typeof PrivacidadTuktukRoute
  PrivacidadVrixoraRoute: typeof PrivacidadVrixoraRoute
  PrivacidadIndexRoute: typeof PrivacidadIndexRoute
}

const PrivacidadRouteChildren: PrivacidadRouteChildren = {
  PrivacidadTuktukRoute: PrivacidadTuktukRoute,
  PrivacidadVrixoraRoute: PrivacidadVrixoraRoute,
  PrivacidadIndexRoute: PrivacidadIndexRoute,
}

const PrivacidadRouteWithChildren = PrivacidadRoute._addFileChildren(
  PrivacidadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PrivacidadRoute: PrivacidadRouteWithChildren,
  ServiciosRoute: ServiciosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolucionesRoute: SolucionesRoute,
  SoporteRoute: SoporteRoute,
  TuktukRoute: TuktukRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
