/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TuktukRouteImport } from './routes/tuktuk'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as SolucionesRouteImport } from './routes/soluciones'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacidadIndexRouteImport } from './routes/privacidad/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as RefCodeRouteImport } from './routes/ref/$code'
import { Route as PrivacidadVrixoraRouteImport } from './routes/privacidad/vrixora'
import { Route as PrivacidadTuktukRouteImport } from './routes/privacidad/tuktuk'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBlogAuthRouteImport } from './routes/admin.blog.auth'

const TuktukRoute = TuktukRouteImport.update({
  id: '/tuktuk',
  path: '/tuktuk',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucionesRoute = SolucionesRouteImport.update({
  id: '/soluciones',
  path: '/soluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadIndexRoute = PrivacidadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivacidadRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const RefCodeRoute = RefCodeRouteImport.update({
  id: '/ref/$code',
  path: '/ref/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadVrixoraRoute = PrivacidadVrixoraRouteImport.update({
  id: '/vrixora',
  path: '/vrixora',
  getParentRoute: () => PrivacidadRoute,
} as any)
const PrivacidadTuktukRoute = PrivacidadTuktukRouteImport.update({
  id: '/tuktuk',
  path: '/tuktuk',
  getParentRoute: () => PrivacidadRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogAuthRoute = AdminBlogAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AdminBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/privacidad': typeof PrivacidadRouteWithChildren
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soluciones': typeof SolucionesRoute
  '/soporte': typeof SoporteRoute
  '/terminos': typeof TerminosRoute
  '/tuktuk': typeof TuktukRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/privacidad/tuktuk': typeof PrivacidadTuktukRoute
  '/privacidad/vrixora': typeof PrivacidadVrixoraRoute
  '/ref/$code': typeof RefCodeRoute
  '/blog/': typeof BlogIndexRoute
  '/privacidad/': typeof PrivacidadIndexRoute
  '/admin/blog/auth': typeof AdminBlogAuthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soluciones': typeof SolucionesRoute
  '/soporte': typeof SoporteRoute
  '/terminos': typeof TerminosRoute
  '/tuktuk': typeof TuktukRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/privacidad/tuktuk': typeof PrivacidadTuktukRoute
  '/privacidad/vrixora': typeof PrivacidadVrixoraRoute
  '/ref/$code': typeof RefCodeRoute
  '/blog': typeof BlogIndexRoute
  '/privacidad': typeof PrivacidadIndexRoute
  '/admin/blog/auth': typeof AdminBlogAuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/privacidad': typeof PrivacidadRouteWithChildren
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soluciones': typeof SolucionesRoute
  '/soporte': typeof SoporteRoute
  '/terminos': typeof TerminosRoute
  '/tuktuk': typeof TuktukRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/privacidad/tuktuk': typeof PrivacidadTuktukRoute
  '/privacidad/vrixora': typeof PrivacidadVrixoraRoute
  '/ref/$code': typeof RefCodeRoute
  '/blog/': typeof BlogIndexRoute
  '/privacidad/': typeof PrivacidadIndexRoute
  '/admin/blog/auth': typeof AdminBlogAuthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/privacidad'
    | '/servicios'
    | '/sitemap.xml'
    | '/soluciones'
    | '/soporte'
    | '/terminos'
    | '/tuktuk'
    | '/admin/blog'
    | '/blog/$slug'
    | '/privacidad/tuktuk'
    | '/privacidad/vrixora'
    | '/ref/$code'
    | '/blog/'
    | '/privacidad/'
    | '/admin/blog/auth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/servicios'
    | '/sitemap.xml'
    | '/soluciones'
    | '/soporte'
    | '/terminos'
    | '/tuktuk'
    | '/admin/blog'
    | '/blog/$slug'
    | '/privacidad/tuktuk'
    | '/privacidad/vrixora'
    | '/ref/$code'
    | '/blog'
    | '/privacidad'
    | '/admin/blog/auth'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/privacidad'
    | '/servicios'
    | '/sitemap.xml'
    | '/soluciones'
    | '/soporte'
    | '/terminos'
    | '/tuktuk'
    | '/admin/blog'
    | '/blog/$slug'
    | '/privacidad/tuktuk'
    | '/privacidad/vrixora'
    | '/ref/$code'
    | '/blog/'
    | '/privacidad/'
    | '/admin/blog/auth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  PrivacidadRoute: typeof PrivacidadRouteWithChildren
  ServiciosRoute: typeof ServiciosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolucionesRoute: typeof SolucionesRoute
  SoporteRoute: typeof SoporteRoute
  TerminosRoute: typeof TerminosRoute
  TuktukRoute: typeof TuktukRoute
  RefCodeRoute: typeof RefCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tuktuk': {
      id: '/tuktuk'
      path: '/tuktuk'
      fullPath: '/tuktuk'
      preLoaderRoute: typeof TuktukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soluciones': {
      id: '/soluciones'
      path: '/soluciones'
      fullPath: '/soluciones'
      preLoaderRoute: typeof SolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad/': {
      id: '/privacidad/'
      path: '/'
      fullPath: '/privacidad/'
      preLoaderRoute: typeof PrivacidadIndexRouteImport
      parentRoute: typeof PrivacidadRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/ref/$code': {
      id: '/ref/$code'
      path: '/ref/$code'
      fullPath: '/ref/$code'
      preLoaderRoute: typeof RefCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad/vrixora': {
      id: '/privacidad/vrixora'
      path: '/vrixora'
      fullPath: '/privacidad/vrixora'
      preLoaderRoute: typeof PrivacidadVrixoraRouteImport
      parentRoute: typeof PrivacidadRoute
    }
    '/privacidad/tuktuk': {
      id: '/privacidad/tuktuk'
      path: '/tuktuk'
      fullPath: '/privacidad/tuktuk'
      preLoaderRoute: typeof PrivacidadTuktukRouteImport
      parentRoute: typeof PrivacidadRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/auth': {
      id: '/admin/blog/auth'
      path: '/auth'
      fullPath: '/admin/blog/auth'
      preLoaderRoute: typeof AdminBlogAuthRouteImport
      parentRoute: typeof AdminBlogRoute
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogAuthRoute: typeof AdminBlogAuthRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogAuthRoute: AdminBlogAuthRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PrivacidadRouteChildren {
  PrivacidadTuktukRoute: typeof PrivacidadTuktukRoute
  PrivacidadVrixoraRoute: typeof PrivacidadVrixoraRoute
  PrivacidadIndexRoute: typeof PrivacidadIndexRoute
}

const PrivacidadRouteChildren: PrivacidadRouteChildren = {
  PrivacidadTuktukRoute: PrivacidadTuktukRoute,
  PrivacidadVrixoraRoute: PrivacidadVrixoraRoute,
  PrivacidadIndexRoute: PrivacidadIndexRoute,
}

const PrivacidadRouteWithChildren = PrivacidadRoute._addFileChildren(
  PrivacidadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  PrivacidadRoute: PrivacidadRouteWithChildren,
  ServiciosRoute: ServiciosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolucionesRoute: SolucionesRoute,
  SoporteRoute: SoporteRoute,
  TerminosRoute: TerminosRoute,
  TuktukRoute: TuktukRoute,
  RefCodeRoute: RefCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
